-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "decisions" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "dataFlow" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "stack" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "gallery" SET DEFAULT ARRAY[]::TEXT[];
